version: '3.9'

services:
  
  db:
    image: postgres:15
    container_name: stock_db
    env_file:
      - .env.prod.docker
    ports:
      - "5432:5432"
  db_test:
    image: postgres:15
    container_name: stock_db_test
    env_file:
      - .env.test.docker
    ports:
      - "5433:5432"
  
  
  app:
    build: 
      context: .
      target: prod
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env.prod.docker
  test:
    build:
      context: .
      target: test
    depends_on:
      - db_test
    env_file:
      - .env.test.docker